# Site settings
title: Matthew Macfarlane
email: m.v.macfarlane@uva.nl
description: Academic webpage of Matthew Macfarlane
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Matthew Macfarlane<br/>
  PhD Candidate, Artificial Intelligence<br/>
  University of Amsterdam

location: >
  University of Amsterdam<br/>
  Science Park 904<br/>
  1098 XH Amsterdam, Netherlands

contact: >
  <a href="mailto:m.v.macfarlane@uva.nl" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Matthew via email</a> <br/>
  <a href="https://github.com/mvmacfarlane"><i class="fa fa-github fa-1x"></i> Visit my GitHub</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: research
  - name: software

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Macfarlane
  first_name: [Matthew]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"



exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
